CREATE TABLE PERSON
(
	ID INTEGER NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL
);

ALTER TABLE PERSON ADD CONSTRAINT PK_PERSON PRIMARY KEY(ID);
ALTER TABLE PERSON ADD CONSTRAINT UNQ_EMAIL_PERSON UNIQUE(EMAIL);

CREATE TABLE PHYSICALPERSON
(
	ID INTEGER NOT NULL,
	PERSON_ID INTEGER NOT NULL,
	SALARY DECIMAL(12,2) NOT NULL,
	DATEBIRTH DATE NOT NULL,
	GENDER CHAR(1) NOT NULL
); 

ALTER TABLE PHYSICALPERSON ADD CONSTRAINT PK_PHYSICALPERSON PRIMARY KEY(ID);
ALTER TABLE PHYSICALPERSON ADD CONSTRAINT FK_PHYSICALPERSON_PERSON FOREIGN KEY(PERSON_ID) REFERENCES PERSON(ID);
ALTER TABLE PHYSICALPERSON ADD CONSTRAINT CHK_SALARY_PHYSICALPERSON CHECK(SALARY >= 0);
ALTER TABLE PHYSICALPERSON ADD CONSTRAINT CHK_DATEBIRTH_PHYSICALPERSON CHECK(DATEBIRTH <=  DATEADD(YEAR, -18, GETDATE()));
ALTER TABLE PHYSICALPERSON ADD CONSTRAINT CHK_GENDER_PHYSICALPERSON CHECK(GENDER = 'M' OR GENDER = 'F');

CREATE TABLE CLIENT
(
	ID INTEGER NOT NULL,
	STATUSCLI CHAR(1) NOT NULL
); 

ALTER TABLE CLIENT ADD CONSTRAINT PK_CLIENT PRIMARY KEY(ID);
ALTER TABLE CLIENT ADD CONSTRAINT CHK_STATUSCLI_CLIENT CHECK(STATUSCLI = 'A' OR STATUSCLI = 'I');

CREATE TABLE CLIENTPHYSICALPERSON
(
	ID INTEGER NOT NULL,
	PHYSICALPERSON_ID INTEGER NOT NULL,
	CLIENT_ID INTEGER NOT NULL
);

ALTER TABLE CLIENTPHYSICALPERSON ADD CONSTRAINT PK_CLIENTPHYSICALPERSON PRIMARY KEY(ID);
ALTER TABLE CLIENTPHYSICALPERSON ADD CONSTRAINT FK_CLIENTPHYSICALPERSON_PHYSICALPERSON FOREIGN KEY(PHYSICALPERSON_ID) REFERENCES PHYSICALPERSON(ID);
ALTER TABLE CLIENTPHYSICALPERSON ADD CONSTRAINT FK_CLIENTPHYSICALPERSON_CLIENT FOREIGN KEY(CLIENT_ID) REFERENCES CLIENT(ID);